# Generated by Django 6.1 on 2026-08-18 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('bulugh_age', models.PositiveSmallIntegerField(blank=True, help_text='Age of religious maturity used as the qada calculation start point.', null=True)),
                ('practice_start_date', models.DateField(blank=True, help_text='Date the user began actively praying / being accountable for qada.', null=True)),
                ('madhhab', models.CharField(choices=[('hanafi', 'Hanafi'), ('shafi', "Shafi'i / Maliki / Hanbali")], default='shafi', max_length=10)),
                ('calculation_method', models.PositiveSmallIntegerField(default=2, help_text='Aladhan API calculation method ID.')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text="Set for child profiles managed under a parent's family mode account.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fajr_enabled', models.BooleanField(default=True)),
                ('dhuhr_enabled', models.BooleanField(default=True)),
                ('asr_enabled', models.BooleanField(default=True)),
                ('maghrib_enabled', models.BooleanField(default=True)),
                ('isha_enabled', models.BooleanField(default=True)),
                ('reminder_minutes_before', models.PositiveSmallIntegerField(default=10)),
                ('qada_reminders_enabled', models.BooleanField(default=True)),
                ('family_digest_enabled', models.BooleanField(default=False, help_text="For parent profiles: daily summary of children's progress.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='core.profile')),
            ],
            options={
                'db_table': 'notification_settings',
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_completed_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to='core.profile')),
            ],
            options={
                'db_table': 'streaks',
            },
        ),
        migrations.CreateModel(
            name='PrayerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('prayer', models.CharField(choices=[('fajr', 'Fajr'), ('dhuhr', 'Dhuhr'), ('asr', 'Asr'), ('maghrib', 'Maghrib'), ('isha', 'Isha')], max_length=10)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_logs', to='core.profile')),
            ],
            options={
                'db_table': 'prayer_logs',
                'indexes': [models.Index(fields=['profile', 'date'], name='prayer_logs_profile_f7b3f0_idx')],
                'constraints': [models.UniqueConstraint(fields=('profile', 'date', 'prayer'), name='unique_prayer_log_per_day')],
            },
        ),
        migrations.CreateModel(
            name='QadaDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer', models.CharField(choices=[('fajr', 'Fajr'), ('dhuhr', 'Dhuhr'), ('asr', 'Asr'), ('maghrib', 'Maghrib'), ('isha', 'Isha')], max_length=10)),
                ('owed_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qada_debts', to='core.profile')),
            ],
            options={
                'db_table': 'qada_debt',
                'constraints': [models.UniqueConstraint(fields=('profile', 'prayer'), name='unique_qada_debt_per_prayer')],
            },
        ),
        migrations.CreateModel(
            name='QadaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer', models.CharField(choices=[('fajr', 'Fajr'), ('dhuhr', 'Dhuhr'), ('asr', 'Asr'), ('maghrib', 'Maghrib'), ('isha', 'Isha')], max_length=10)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qada_logs', to='core.profile')),
            ],
            options={
                'db_table': 'qada_logs',
                'indexes': [models.Index(fields=['profile', 'prayer'], name='qada_logs_profile_215667_idx')],
            },
        ),
    ]
