# Generated by Django 6.1 on 2026-08-19 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationsettings',
            old_name='asr_enabled',
            new_name='enabled',
        ),
        migrations.RenameField(
            model_name='qadadebt',
            old_name='owed_count',
            new_name='remaining_count',
        ),
        migrations.RenameField(
            model_name='streak',
            old_name='last_completed_date',
            new_name='last_calculated_date',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='dhuhr_enabled',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='fajr_enabled',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='family_digest_enabled',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='isha_enabled',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='maghrib_enabled',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='qada_reminders_enabled',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='reminder_minutes_before',
        ),
        migrations.RemoveField(
            model_name='prayerlog',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='prayerlog',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='streak',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='muted_by_parent',
            field=models.BooleanField(default=False, help_text="Parent can mute a child's notifications from the family dashboard."),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='tone',
            field=models.CharField(choices=[('standard', 'Standard'), ('gentle', 'Gentle')], default='standard', max_length=10),
        ),
        migrations.AddField(
            model_name='prayerlog',
            name='status',
            field=models.CharField(choices=[('unmarked', 'Unmarked'), ('done', 'Done'), ('late', 'Late')], default='unmarked', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional. Shapes reminder tone only, nothing else.', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='qada_enabled',
            field=models.BooleanField(default=True, help_text='Off for children just building the habit; on by default for adult/self profiles.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('self', 'Self'), ('child', 'Child')], default='self', max_length=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='madhhab',
            field=models.CharField(choices=[('hanafi', 'Hanafi'), ('shafi', "Shafi'i / Maliki / Hanbali")], default='hanafi', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'self')), fields=('user', 'type'), name='one_self_profile_per_user'),
        ),
    ]
